# fly.toml app configuration file generated for fly-fastapi-trends on 2025-04-13T15:41:19Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-fastapi-trends'
primary_region = 'otp'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
